export const Data = [
    {"DeckNumber":1,"name":"Lamball","element":"Neutral","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Lamball.png"},
    {"DeckNumber":2,"name":"Cattiva","element":"Neutral","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Cattiva.png"},
    {"DeckNumber":3,"name":"Chikipi","element":"Neutral","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Chikipi.png"},
    {"DeckNumber":4,"name":"Lifmunk","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Lifmunk.png"},
    {"DeckNumber":5,"name":"Foxparks","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Foxparks.png"},
    {"DeckNumber":6,"name":"Fuack","element":"Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Fuack.png"},
    {"DeckNumber":7,"name":"Sparkit","element":"Electric","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Sparkit.png"},
    {"DeckNumber":8,"name":"Tanzee","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Tanzee.png"},
    {"DeckNumber":9,"name":"Rooby","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Rooby.png"},
    {"DeckNumber":10,"name":"Pengullet","element":"Water/Ice","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Pengullet.png"},
    {"DeckNumber":11,"name":"Penking","element":"Water/Ice","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Penking.png"},
    {"DeckNumber":12,"name":"Jolthog","element":"Electric","role":"Generating Electricity", imageUrl: "https://paldeck.mael.tech/pals/icons/Jolthog.png"},
    {"DeckNumber":12.5,"name":"Jolthog Cryst","element":"Ice","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Jolthog%20Cryst.png"},
    {"DeckNumber":13,"name":"Gumoss","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Gumoss.png"},
    {"DeckNumber":14,"name":"Vixy","element":"Neutral","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Vixy.png"},
    {"DeckNumber":15,"name":"Hoocrates","element":"Dark","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Hoocrates.png"},
    {"DeckNumber":16,"name":"Teafant","element":"Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Teafant.png"},
    {"DeckNumber":17,"name":"Depresso","element":"Dark","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Depresso.png"},
    {"DeckNumber":18,"name":"Cremis","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Cremis.png"},
    {"DeckNumber":19,"name":"Daedream","element":"Dark","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Daedream.png"},
    {"DeckNumber":20,"name":"Rushoar","element":"Ground","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Rushoar.png"},
    {"DeckNumber":21,"name":"Nox","element":"Dark","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Nox.png"},
    {"DeckNumber":22,"name":"Fuddler","element":"Ground","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Fuddler.png"},
    {"DeckNumber":23,"name":"Killamari","element":"Dark","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Killamari.png"},
    {"DeckNumber":24,"name":"Mau","element":"Dark","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Mau.png"},
    {"DeckNumber":24.5,"name":"Mau Cryst","element":"Ice","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Mau%20Cryst.png"},
    {"DeckNumber":25,"name":"Celaray","element":"Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Celaray.png"},
    {"DeckNumber":26,"name":"Direhowl","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Direhowl.png"},
    {"DeckNumber":27,"name":"Tocotoco","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Tocotoco.png"},
    {"DeckNumber":28,"name":"Flopie","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Flopie.png"},
    {"DeckNumber":29,"name":"Mozzarina","element":"Neutral","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Mozzarina.png"},
    {"DeckNumber":30,"name":"Bristla","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Bristla.png"},
    {"DeckNumber":31,"name":"Gobfin","element":"Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Gobfin.png"},
    {"DeckNumber":32,"name":"Hangyu","element":"Ground","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Hangyu.png"},
    {"DeckNumber":33,"name":"Mossanda","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Mossanda.png"},
    {"DeckNumber":34,"name":"Woolipop","element":"Neutral","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Woolipop.png"},
    {"DeckNumber":35,"name":"Caprity","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Caprity.png"},
    {"DeckNumber":36,"name":"Melpaca","element":"Neutral","role":"Farming", imageUrl: "https://paldeck.mael.tech/pals/icons/Melpaca.png"},
    {"DeckNumber":37,"name":"Eikthyrdeer","element":"Neutral","role":"Lumbering", imageUrl: "https://paldeck.mael.tech/pals/icons/Eikthyrdeer.png"},
    {"DeckNumber":38,"name":"Nitewing","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Nitewing.png"},
    {"DeckNumber":39,"name":"Ribbuny","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Ribbuny.png"},
    {"DeckNumber":40,"name":"Incineram","element":"Fire/Dark","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Incineram.png"},
    {"DeckNumber":41,"name":"Cinnamoth","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Cinnamoth.png"},
    {"DeckNumber":42,"name":"Arsox","element":"Fire","role":"Lumbering", imageUrl: "https://paldeck.mael.tech/pals/icons/Arsox.png"},
    {"DeckNumber":43,"name":"Dumud","element":"Ground","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Dumud.png"},
    {"DeckNumber":44,"name":"Cawgnito","element":"Dark","role":"Lumbering", imageUrl: "https://paldeck.mael.tech/pals/icons/Cawgnito.png"},
    {"DeckNumber":45,"name":"Leezpunk","element":"Dark","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Leezpunk.png"},
    {"DeckNumber":46,"name":"Loupmoon","element":"Dark","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Loupmoon.png"},
    {"DeckNumber":47,"name":"Galeclaw","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Galeclaw.png"},
    {"DeckNumber":48,"name":"Robinquill","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Robinquill.png"},
    {"DeckNumber":49,"name":"Gorirat","element":"Neutral","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Gorirat.png"},
    {"DeckNumber":50,"name":"Beegarde","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Beegarde.png"},
    {"DeckNumber":51,"name":"Elizabee","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Elizabee.png"},
    {"DeckNumber":52,"name":"Grintale","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Grintale.png"},
    {"DeckNumber":53,"name":"Swee","element":"Ice","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Swee.png"},
    {"DeckNumber":54,"name":"Sweepa","element":"Ice","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Sweepa.png"},
    {"DeckNumber":55,"name":"Chillet","element":"Ice/Dragon","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Chillet.png"},
    {"DeckNumber":56,"name":"Univolt","element":"Electric","role":"Generating Electricity", imageUrl: "https://paldeck.mael.tech/pals/icons/Univolt.png"},
    {"DeckNumber":58,"name":"Pyrin","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Pyrin.png"},
    {"DeckNumber":59,"name":"Reindrix","element":"Ice","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Reindrix.png"},
    {"DeckNumber":60,"name":"Rayhound","element":"Electric","role":"Generating Electricity", imageUrl: "https://paldeck.mael.tech/pals/icons/Rayhound.png"},
    {"DeckNumber":62,"name":"Dazzi","element":"Electric","role":"Generating Electricity", imageUrl: "https://paldeck.mael.tech/pals/icons/Dazzi.png"},
    {"DeckNumber":63,"name":"Lunaris","element":"Neutral","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Lunaris.png"},
    {"DeckNumber":64,"name":"Dinossom","element":"Grass/Dragon","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Dinossom.png"},
    {"DeckNumber":65,"name":"Surfent","element":"Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Surfent.png"},
    {"DeckNumber":66,"name":"Maraith","element":"Dark","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Maraith.png"},
    {"DeckNumber":67,"name":"Digtoise","element":"Ground","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Digtoise.png"},
    {"DeckNumber":68,"name":"Tombat","element":"Dark","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Tombat.png"},
    {"DeckNumber":69,"name":"Lovander","element":"Neutral","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Lovander.png"},
    {"DeckNumber":70,"name":"Flambelle","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Flambelle.png"},
    {"DeckNumber":71,"name":"Vanwyrm","element":"Fire/Dark","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Vanwyrm.png"},
    {"DeckNumber":72,"name":"Bushi","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Bushi.png"},
    {"DeckNumber":73,"name":"Beakon","element":"Electric","role":"Transporting", imageUrl: "https://paldeck.mael.tech/pals/icons/Beakon.png"},
    {"DeckNumber":74,"name":"Ragnahawk","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Ragnahawk.png"},
    {"DeckNumber":75,"name":"Katress","element":"Dark","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Katress.png"},
    {"DeckNumber":76,"name":"Wixen","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Wixen.png"},
    {"DeckNumber":77,"name":"Verdash","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Verdash.png"},
    {"DeckNumber":78,"name":"Vaelet","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Vaelet.png"},
    {"DeckNumber":79,"name":"Sibelyx","element":"Ice","role":"Medicine", imageUrl: "https://paldeck.mael.tech/pals/icons/Sibelyx.png"},
    {"DeckNumber":80,"name":"Elphidran","element":"Dragon","role":"Lumbering", imageUrl: "https://paldeck.mael.tech/pals/icons/Elphidran.png"},
    {"DeckNumber":81,"name":"Kelpsea","element":"Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Kelpsea.png"},
    {"DeckNumber":82,"name":"Azurobe","element":"Water/Dragon","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Azurobe.png"},
    {"DeckNumber":83,"name":"Cryolinx","element":"Ice","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Cryolinx.png"},
    {"DeckNumber":84,"name":"Blazehowl","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Blazehowl.png"},
    {"DeckNumber":85,"name":"Relaxaurus","element":"Dragon/Water","role":"Transporting", imageUrl: "https://paldeck.mael.tech/pals/icons/Relaxaurus.png"},
    {"DeckNumber":86,"name":"Broncherry","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Broncherry.png"},
    {"DeckNumber":87,"name":"Petallia","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Petallia.png"},
    {"DeckNumber":88,"name":"Reptyro","element":"Fire/Ground","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Reptyro.png"},
    {"DeckNumber":89,"name":"Kingpaca","element":"Neutral","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Kingpaca.png"},
    {"DeckNumber":90,"name":"Mammorest","element":"Grass","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Mammorest.png"},
    {"DeckNumber":91,"name":"Wumpo","element":"Ice","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Wumpo.png"},
    {"DeckNumber":92,"name":"Warsect","element":"Ground/Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Warsect.png"},
    {"DeckNumber":93,"name":"Fenglope","element":"Neutral","role":"Lumbering", imageUrl: "https://paldeck.mael.tech/pals/icons/Fenglope.png"},
    {"DeckNumber":94,"name":"Felbat","element":"Dark","role":"Medicine", imageUrl: "https://paldeck.mael.tech/pals/icons/Felbat.png"},
    {"DeckNumber":95,"name":"Quivern","element":"Dragon","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Quivern.png"},
    {"DeckNumber":96,"name":"Blazamut","element":"Fire","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Blazamut.png"},
    {"DeckNumber":97,"name":"Helzephyr","element":"Dark","role":"Transporting", imageUrl: "https://paldeck.mael.tech/pals/icons/Helzephyr.png"},
    {"DeckNumber":98,"name":"Astegon","element":"Dragon/Dark","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Astegon.png"},
    {"DeckNumber":99,"name":"Menasting","element":"Dark/Ground","role":"Mining", imageUrl: "https://paldeck.mael.tech/pals/icons/Menasting.png"},
    {"DeckNumber":100,"name":"Anubis","element":"Ground","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Anubis.png"},
    {"DeckNumber":101,"name":"Jormuntide","element":"Dragon/Water","role":"Watering", imageUrl: "https://paldeck.mael.tech/pals/icons/Jormuntide.png"},
    {"DeckNumber":102,"name":"Suzaku","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Suzaku.png"},
    {"DeckNumber":103,"name":"Grizzbolt","element":"Electric","role":"Handiwork", imageUrl: "https://paldeck.mael.tech/pals/icons/Grizzbolt.png"},
    {"DeckNumber":104,"name":"Lyleen","element":"Grass","role":"Planting", imageUrl: "https://paldeck.mael.tech/pals/icons/Lyleen.png"},
    {"DeckNumber":105,"name":"Faleris","element":"Fire","role":"Kindling", imageUrl: "https://paldeck.mael.tech/pals/icons/Faleris.png"},
    {"DeckNumber":106,"name":"Orserk","element":"Dragon/Electric","role":"Generating", imageUrl: "https://paldeck.mael.tech/pals/icons/Orserk.png"},
    {"DeckNumber":107,"name":"Shadowbeak","element":"Dark","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Shadowbeak.png"},
    {"DeckNumber":110,"name":"Frostallion","element":"Ice","role":"Cooling", imageUrl: "https://paldeck.mael.tech/pals/icons/Frostallion.png"},
    {"DeckNumber":111,"name":"Jetragon","element":"Dragon","role":"Gathering", imageUrl: "https://paldeck.mael.tech/pals/icons/Jetragon.png"}

   
  ];
  